export default {
    INTRODUCAO: '4',
    INTRODUCAO_DIALOG: '3',
    MICROMUNDO_I: '7',
    MICROMUNDO_I_DIALOG: '3',
    MICROMUNDO_II: '8',
    MICROMUNDO_II_DIALOG: '3' ,
    MICROMUNDO_III: '8',
    MICROMUNDO_III_DIALOG: '3' ,
    CONSIDERACOES: '1',
    CONSIDERACOES_DIALOG: '3'
}